BASE_URL = "https://tobeto.com/giris"
VALID_LOGIN_XLSX = "data/Login.xlsx"
INVALID_LOGIN_XLSX = "data/Login1.xlsx"
REGISTER_XLSX = "data/Register.xlsx"
REGISTER1_XLSX = "data/Register1.xlsx"
REGISTER2_XLSX = "data/Register2.xlsx"
EMPTYMESSAGE_XPATH_1 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[1]"
EMPTYMESSAGE_XPATH_2 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[2]"
EMPTYMESSAGE = "Doldurulması zorunlu alan*"
EMAIL_NAME = "email"
PASSWORD_NAME ="password"
LOGIN_BUTTON_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
VALID_LOGIN_XPATH = "//*[@id='__next']/div/div[2]/div/div[2]"
VALID_LOGIN = "• Giriş başarılı."
INVALID_LOGIN_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
INVALID_LOGIN = "• Geçersiz e-posta veya şifre."
FIRSTNAME_NAME = "firstName"
LASTNAME_NAME = "lastName"
PASSWORDAGAIN_NAME = "passwordAgain"
PHONE_NUMBER_ID = "phoneNumber"
RECAPTCHA_XPATH = "//*[@id='recaptcha-anchor']/div[1]"
FINAL_REGISTER_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER = "Kayıt Ol"
REGISTER_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
CANT_REGISTER = "• Girdiğiniz e-posta adresi ile kayıtlı üyelik bulunmaktadır."
CANT_REGISTER_XPATH = "//*[@id='__next']/div/div[2]/div/div[2])"
INVALID_EMAIL_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/p"
INVALID_EMAIL = "Geçersiz e-posta adresi*"
MIN_PHONE_NUMBER_XPATH = "/html/body/div[5]/div/div/div/div/div/label[4]/small/p"
MIN_PHONE_NUMBER = "En az 10 karakter girmelisiniz."
MAX_PHONE_NUMBER_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
MAX_PHONE_NUMBER = "En fazla 10 karakter girebilirsiniz. "
EMPTY_PHONE_NUMBER_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p[1]"
EMPTY_PHONE_NUMBER = "Doldurulması zorunlu alan*"
MISSING_PASSWORD = "• Şifreniz en az 6 karakterden oluşmalıdır."
UNMATCHED_PASSWORD = "• Şifreler eşleşmedi"
INVALID_INFORMATIONS = "• 2 errors occured"
SURVEY_BUTTON_XPATH = "//*[@id='mySurvey-tab']"
SURVEY_MESSAGE_XPATH = "//*[@id='mySurvey-tab-pane']/div/div/p"
SURVEY_MESSAGE = "Atanmış herhangi bir anketiniz bulunmamaktadır"
SURVEY_XLSX = "data/Survey.xlsx"
CATALOG_BUTTON_XPATH = "//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
EDUCATION_ID ="search"
SEARCH_BUTTON= "//*[@id='__next']/div/main/div[1]/div/div/div/div[2]/button"
CATALOG_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]/div/div/p"
CATALOG_MESSAGE = "Aradığınız kriterlere uygun içerik bulunamadı."
MY_PROFILE_XPATH= "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
EDIT_BUTTON_XPATH = "//*[@id='__next']/div/main/div/div[1]/div/span"
SAVE_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/button"
ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/span"
ERROR_MESSAGE = "Doldurulması zorunlu alan*"
TC_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/span"
TC__MESSAGE = "*Aboneliklerde fatura için doldurulması zorunlu alan"
EXPERIENCE_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/a[2]/span[2]"
ORGANIZATION_NAME_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[1]/input"
POSITION_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[2]/input"
SECTOR_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[3]/input"
CITY_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[4]/select"
STARTUP_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[5]/div/div/input"
CONTINUED_XPATH = "//*[@id='__next']/div/main/section/div/div/div[2]/form/div/div[6]/label[2]/input"
EXPERIENCE_MESSAGE_XPATH = "//*[@id='__next']/div/div[3]/div/div[2]"
EXPERIENCE_MESSAGE = "• Deneyim eklendi."