BASE_URL = "https://tobeto.com/giris"
Login_xlsx = "data/Login.xlsx"
Login1_xlsx = "data/Login1.xlsx"
Register_xlsx = "data/Register.xlsx"
Register1_xlsx = "data/Register1.xlsx"
Register2_xlsx = "data/Register2.xlsx"
EMPTYMESSAGE_XPATH_1 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[1]"
EMPTYMESSAGE_XPATH_2 = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p[2]"
EMPTYMESSAGE = "Doldurulması zorunlu alan*"
EMAIL_NAME = "email"
PASSWORD_NAME ="password"
LOGIN_BUTTON_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/form/button"
VALID_LOGIN_XPATH = "//*[@id='__next']/div/div[2]/div/div[2]"
VALID_LOGIN = "• Giriş başarılı."
INVALID_LOGIN_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
INVALID_LOGIN = "• Geçersiz e-posta veya şifre."
FIRSTNAME_NAME = "firstName"
LASTNAME_NAME = "lastName"
PASSWORDAGAIN_NAME = "passwordAgain"
PHONE_NUMBER_ID = "phoneNumber"
RECAPTCHA_XPATH = "//*[@id='recaptcha-anchor']/div[1]"
FINAL_REGISTER_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER = "Kayıt Ol"
REGISTER_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
CANT_REGISTER = "• Girdiğiniz e-posta adresi ile kayıtlı üyelik bulunmaktadır."
CANT_REGISTER_XPATH = "//*[@id='__next']/div/div[2]/div/div[2])"
INVALID_EMAIL_XPATH ="//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/p"
INVALID_EMAIL = "Geçersiz e-posta adresi*"
MIN_PHONE_NUMBER_XPATH = "/html/body/div[5]/div/div/div/div/div/label[4]/small/p"
MIN_PHONE_NUMBER = "En az 10 karakter girmelisiniz."
MAX_PHONE_NUMBER_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
MAX_PHONE_NUMBER = "En fazla 10 karakter girebilirsiniz. "
EMPTY_PHONE_NUMBER_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p[1]"
EMPTY_PHONE_NUMBER = "Doldurulması zorunlu alan*"
MISSING_PASSWORD = "• Şifreniz en az 6 karakterden oluşmalıdır."
UNMATCHED_PASSWORD = "• Şifreler eşleşmedi"
INVALID_INFORMATIONS = "• 2 errors occured"

