# Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
# from constants import globalConstants as c

# class TestExperinece():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.driver.get(c.BASE_URL)
#     self.driver.maximize_window()
#     self.vars = {}
  
#   def teardown_method(self, method):
#     self.driver.quit()
  
#   def test_deneyimlerim(self):
#     self.driver.find_element(By.NAME, c.EMAIL_NAME).send_keys(c.EMAIL)
#     self.driver.find_element(By.NAME, c.PASSWORD_NAME).send_keys(c.PASSWORD)
#     WebDriverWait(self.driver, 5).until(expected_conditions.element_to_be_clickable((By.XPATH, c.LOGIN_BUTTON_XPATH))).click()
#     time.sleep(5)
#     WebDriverWait(self.driver, 10).until(expected_conditions.visibility_of_element_located((By.XPATH, c.PROFIL_INFORMATION_BUTTON_XPATH))).click()
#     self.driver.find_element(By.LINK_TEXT, "Profil Bilgileri").click()
#     WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, c.PROFIL_BILGILER_BUTTON_CSS)))
#     self.driver.find_element(By.CSS_SELECTOR, c.DENEYIMLERIM_SIDE_BUTTON_XPATH).click()
#     time.sleep(1)
#     WebDriverWait(self.driver,10).until(expected_conditions.visibility_of_element_located((By.XPATH,c.KAYDET_BUTTON_XPATH))).click()
#     assert self.driver.find_element(By.CSS_SELECTOR, c.EXPERIENCE_ERROR_MESSAGE_XPATH).text == c.ERROR_MESSAGE
  
