# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import globalConstants as c
from selenium.webdriver.support import expected_conditions as ec 

class TestCatalog():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.get(c.BASE_URL)
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_catalog(self):
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.NAME,c.EMAIL_NAME))).send_keys(c.EMAIL)
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.NAME,c.PASSWORD_NAME))).send_keys(c.PASSWORD)
    self.driver.find_element(By.XPATH,c.LOGIN_BUTTON_XPATH).click()
    time.sleep(5)
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.XPATH,c.CATALOG_NAVBAR_BUTTON_XPATH))).click()
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.ID,"search"))).send_keys("hibrit yaşamda duyguyu düzenleme")
    WebDriverWait(self.driver, 5).until(ec.visibility_of_element_located((By.XPATH,c.CATALOG_SEARCH_BUTTON_XPATH))).click()
    education_items = WebDriverWait(self.driver, 10).until(ec.visibility_of_element_located((By.CLASS_NAME,"education-box-new")))
    assert "Hibrit Yaşamda Duyguyu Düzenleme" in education_items.text
    


  
